services:
  - type: web
    name: rsa-secure-messaging
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5500
